### ISSUE TITLE
In firefox 35.0.1 (Mac) it still doesn't work

### ISSUE THREAD

**Issue by chrisfp** [filaraujo/akyral-waypoint#2]
Thank you for your very fast fixing :)

unfortunately, in my firefox it still doesn't work. commenting out line 155 "return (window.getComputedStyle(el) || {}).overflow === 'auto';" resolves the problem for me. the error-message in firefox is: "TypeError: Argument 1 of Window.getComputedStyle does not implement interface Element."

**Comment by filaraujo** [comment]
issue resolved
